# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKjWAR4roE0grFSLBBamBTy8UffHascW
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

# Cargar los datos desde un archivo CSV
archivo_csv = 'sectors_outsourcing.csv'  # Nombre del archivo
df = pd.read_csv(archivo_csv)

# Convertir la columna "Frecuencia_Outsourcing(%)" a valores numéricos
df["Frecuencia_Outsourcing(%)"] = df["Frecuencia_Outsourcing(%)"].astype(float)

# Crear un índice ficticio como variable independiente
df = df.sort_values(by="Frecuencia_Outsourcing(%)", ascending=False).reset_index(drop=True)
df["Ranking"] = np.arange(1, len(df) + 1)

# Separar las variables independiente (Ranking) y dependiente (Frecuencia_Outsourcing(%))
X = df[["Ranking"]].values  # Variable independiente
y = df["Frecuencia_Outsourcing(%)"].values  # Variable dependiente

# Crear y ajustar el modelo de regresión lineal
model = LinearRegression()
model.fit(X, y)

# Generar predicciones
y_pred = model.predict(X)

# Mostrar los coeficientes del modelo
print("Pendiente (coeficiente):", model.coef_[0])
print("Intercepto:", model.intercept_)

# Graficar los datos reales y la regresión lineal
plt.figure(figsize=(12, 6))
plt.scatter(df["Ranking"], df["Frecuencia_Outsourcing(%)"], color="blue", label="Datos reales")
plt.plot(df["Ranking"], y_pred, color="red", label="Regresión Lineal")

# Etiquetas y título
plt.xlabel("Ranking de Sectores")
plt.ylabel("Frecuencia de Outsourcing (%)")
plt.title("Regresión Lineal sobre Frecuencia de Outsourcing por Sector")
plt.legend()
plt.grid(True)
plt.tight_layout()

# Mostrar el gráfico
plt.show()